# Site settings
title: Hyde Solutions
description: A blog about my security research and projects I work on
baseurl: "/"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brian Hyde 
user_description: Security Researcher, Programmer, Full Stack Developer, & Businessman.
user_title: Security Researcher
email: brian@hyde.solutions
twitter_username: 0xHyde
github_username:  h-yde
